---

# This script installs some basic programs + sets up kinit and VPN. You need to download files and certificates beforehand from the google drive
- name: basic setup, kinit & VPN
  hosts: localhost
  become: true
  become_user: root

  tasks:

# This finds the name of the user's home directory
    - name: find the name of the user
      become: false
      command: whoami
      register: host_username

# This upgrades all the packages
    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest

# This enables repository to download newdoc & downloads newdoc
# Works for Fedora 31 or newer cause Marek doesn't support anything older
    - name: enable mareksu/newdoc repository
      command: dnf copr enable mareksu/newdoc -y
      args:
        warn: false

    - name: install newdoc
      dnf:
        name: python3-newdoc
        state: latest

# This downloads Flatpack & enables Flathub remote so we can install BlueJeans
    - name: install flatpak
      dnf:
        name: flatpak
        state: latest

    - name: add Flathub flatpak remote
      become: false
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: install bluejeans
      become: false
      flatpak:
        name: com.bluejeans.BlueJeans
        state: present

# This installs some basics
# TODO: idk if we need anything else. we probs do
    - name: install basics
      dnf:
        name:
          - rubygem-asciidoctor
          - virt-manager
          - mediawriter
          - gimp
          - nano
          - vim
          - htop
        state: latest

# This sets up VPN
    - name: install openvpn (prerequisite)
      dnf:
        name:
          - NetworkManager-openvpn
          - NetworkManager-openvpn-gnome
        state: latest

    - name: find .crt files in ~/Downloads/
      become: false
      debug: msg={{ lookup('fileglob', '~/Downloads/*.crt') }}

    - name: copy each .crt file that matches the given pattern to /etc/pki/tls/certs/
      copy:
        src: "{{ item }}"
        dest: "/etc/pki/tls/certs/2015-RH-IT-Root-CA.pem"
        mode: 0644
      with_fileglob:
        - "/home/{{ host_username.stdout }}/Downloads/*.crt"

# TODO: maybe redo with find: module
#    - name: move and rename IT Root CA Certificate
#      command: mv /home/{{ host_username.stdout }}/Downloads/RH-IT-Root-CA.crt /etc/pki/tls/certs/2015-RH-IT-Root-CA.pem

# TODO: redo with propper dir structure
    - name: find .ovpn files in ~/Downloads/
      become: false
      debug: msg={{ lookup('fileglob', '~/Downloads/*.ovpn') }}

    - name: copy each .ovpn file that matches the given pattern to /etc/NetworkManager/system-connections/
      copy:
        src: "{{ item }}"
        dest: "/etc/NetworkManager/system-connections/"
        mode: 0600
      with_fileglob:
        - "/home/{{ host_username.stdout }}/Downloads/*.ovpn"

    - name: restore default SELinux context recrusively (verbose + force)
      command: "{{ item }}"
      loop:
        - restorecon -RvF /etc/pki/tls/certs/
        - restorecon -RvF /etc/NetworkManager/system-connections/

    - name: change file permissions for .pem
      file:
        path: /etc/pki/tls/certs/2015-RH-IT-Root-CA.pem
        mode: 0644

    - name: ensure /etc/NetworkManager/system-connections directory is 0755
      vars:
        path: /etc/NetworkManager/system-connections
      command: find {{ path }} -type d -exec chmod -c 0755 {} \;
      register: chmod_result
      changed_when: "chmod_result.stdout != \"\""

    - name: ensure .ovpn files are 0600
      vars:
        path: /etc/NetworkManager/system-connections
      command: find {{ path }} -type f -exec chmod -c 0600 {} \;
      register: chmod_result
      changed_when: "chmod_result.stdout != \"\""

    - name: reload connection
      command: nmcli connection reload

# This sets up kinit
# Works for older Fedora versions (30&31). Fedora 32 lacks the dependency package pam_krb5. If u pull it from the rpm archive it requires another pam package that is lacking. Oh well

# I know you can install the rpm by name but this is more fun
    - name: get name of the .rpm
      find:
        path: /home/{{ host_username.stdout }}/Downloads
        patterns: "rhit*"
      register: find_results_rhit

    - name: ceate a list of the rpms to use with the yum install command
      set_fact:
        rpm_list: "{{ find_results_rhit.files | map(attribute='path') | list }}"

    - name: install rpm_list with yum
      become: true
      yum:
        name: "{{ rpm_list }}"
        state: present

    - name: run autoconfig
      command:  /usr/share/rhit-iam/rhit_legacy_authconfig
